#pragma once
#include "Arduino.h"

#define MODBUS_RO_PIN D10  // RX
#define MODBUS_RE_PIN D11  // EN
#define MODBUS_DE_PIN D11  // EN
#define MODBUS_DI_PIN D12  // TX

enum WriteHoldingRegisterIndex {
  ADC_REGISTER,
  VOLT_REGISTER,
  DO_REGISTER,
  OUT_FREQUENCY_REGISTER,
  PWM_OUT_REGISTER,
  EEPROM_WRITE_COUNT_REGISTER,
  EEPROM_WRITE_LIMIT_REGISTER,
  EEPROM_HEALTH_REGISTER,
  EEPROM_TOTAL_BAD_SECTOR_REGISTER,
  WRITE_HOLDING_REGISTER_LEN
};

enum ReadHoldingRegisterIndex {
  CALIBRATION_REGISTER,
  IN_FREQUENCY_REGISTER,
  DO_THRESHOLD_REGISTER,
  ABOVE_THESHOLD_REGISTER,
  BELOW_THESHOLD_REGISTER,
  TRANSITION_TIME_REGISTER,
  READ_HOLDING_REGISTER_LEN
};

enum ReadCoils {
  POWER_COIL,
  AUTO_COIL,
  READ_COIL_LEN
};

void initModbusConfig();