#define ENABLE_MODULE_SERIAL_ENHANCED

#include "StepperSlave.h"

#define SLAVE_ADDR X_AXIS
#define CLK_PIN 10
#define CW_PIN 11

#if SLAVE_ADDR == X_AXIS
#define EN_PIN 12
#pragma message("[INFO]: ENA PIN 12")
#else
#define EN_PIN NOT_CONNECTED
#pragma message("[INFO]: ENA PIN DISABLE")
#endif

#define RX_PIN 8
#define TX_PIN 9
#define SENSOR_PIN 6

#if SLAVE_ADDR == T_AXIS
#define BRAKE_PIN 7
#define INVERT_BRAKE HIGH_LOGIC_BRAKE
#define INVERT_ENABLE HIGH_LOGIC_ENABLE
#define ENABLE_ENGAGE_DELAY NO_DELAY
#define ENABLE_RELEASE_DELAY NO_DELAY
#define BRAKE_ENGAGE_DELAY 1500
#define BRAKE_RELEASE_DELAY 250
#else
#define BRAKE_PIN NOT_CONNECTED
#define INVERT_BRAKE HIGH_LOGIC_BRAKE
#define INVERT_ENABLE LOW_LOGIC_ENABLE
#define ENABLE_ENGAGE_DELAY NO_DELAY
#define ENABLE_RELEASE_DELAY NO_DELAY
#define BRAKE_ENGAGE_DELAY NO_DELAY
#define BRAKE_RELEASE_DELAY NO_DELAY
#endif

#define INDICATOR_PIN 13

StepperSlave slave(SLAVE_ADDR, RX_PIN, TX_PIN, CLK_PIN, CW_PIN, EN_PIN, SENSOR_PIN,
                   BRAKE_PIN, INVERT_BRAKE, INDICATOR_PIN, INVERT_ENABLE,
                   BRAKE_RELEASE_DELAY, BRAKE_ENGAGE_DELAY,
                   ENABLE_RELEASE_DELAY, ENABLE_ENGAGE_DELAY);

// CMD_STAR     = 1 // x;1;200
// CMD_ZERO     = 2 // x;2
// CMD_RESET    = 5
// CMD_SETSPEED = 6

void setup() {
  slave.begin();
}

void loop() {
  slave.update();
}